name: CI Deployment

on:
  pull_request:
    types:
      - closed
    branches:
      - master
      - stage
      - dev

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      environment_override:
        type: choice
        description: Enter environment override
        required: false
        options: 
        - ''
        - d1
        - q1
        - q2
        - l1
  

# env:
#   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#   PAT: ${{ secrets.PAT }}

env:
  BRANCH_NAME: ${{ github.event.pull_request.base.ref || github.head_ref || github.ref_name }}

jobs:

  build:
    runs-on: ubuntu-latest
    outputs:
      ENVIRONMENT_NAME: ${{ steps.environment.outputs.ENVIRONMENT_NAME }}
      
    steps:
          
      - name: Set environment for workflow_dispatch event
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          if [ "${{ inputs.environment_override }}" != "" ]; then
            echo "ENVIRONMENT_NAME=${{ inputs.environment_override }}" >> $GITHUB_ENV
          elif [ "${{ env.BRANCH_NAME }}" == "dev" ]; then
            echo "ENVIRONMENT_NAME=d1" >> $GITHUB_ENV
          elif [ "${{ env.BRANCH_NAME }}" == "stage" ]; then
            echo "ENVIRONMENT_NAME=q1" >> $GITHUB_ENV
          elif [ "${{ env.BRANCH_NAME }}" == "master" ]; then
            echo "ENVIRONMENT_NAME=q2" >> $GITHUB_ENV
          else
            echo "Error: Invalid base_branch - need to specfiy environment override"
            exit 1
          fi
      
      - name: Set environment for pull_request event
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          if [ "${{ env.BRANCH_NAME }}" == "dev" ]; then
            echo "ENVIRONMENT_NAME=d1" >> $GITHUB_ENV
          elif [ "${{ env.BRANCH_NAME }}" == "stage" ]; then
            echo "ENVIRONMENT_NAME=q1" >> $GITHUB_ENV
          elif [ "${{ env.BRANCH_NAME }}" == "master" ]; then
            echo "ENVIRONMENT_NAME=q2" >> $GITHUB_ENV
          else
            #TODO what happens for l1?
            echo "Error: Invalid base_branch"
            exit 1
          fi
      
      - name: Output environment
        id: environment
        run: |
          echo "ENVIRONMENT_NAME=${{ env.ENVIRONMENT_NAME }}" >> $GITHUB_OUTPUT;

      - name: Get commit hash
        id: branch-info
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/${{ github.repository }}/branches/${{ env.BRANCH_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: "echo branch-info: '${{ steps.branch-info.outputs.data }}'"

      - name: Print commit hash
        run: |
          COMMIT_HASH=$(echo "${{ fromJson(steps.branch-info.outputs.data).commit.sha }}")
          echo "COMMIT_HASH=$COMMIT_HASH" >> $GITHUB_ENV

      - uses: actions/checkout@v3
        with:
          ref: refs/heads/${{ env.BRANCH_NAME }}
          #${{ env.COMMIT_HASH }}

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
  
  deployment:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: ${{ needs.build.outputs.ENVIRONMENT_NAME }}
      url: https://example.com/environments/${{ needs.build.outputs.ENVIRONMENT_NAME }}
    
    steps:
      - name: Set environment
        run: |
          echo "ENVIRONMENT_NAME=${{ needs.build.outputs.ENVIRONMENT_NAME }}" >> $GITHUB_ENV;

      - name: Get commit hash
        id: branch-info
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/${{ github.repository }}/branches/${{ env.BRANCH_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Print commit hash
        run: |
          COMMIT_HASH=$(echo "${{ fromJson(steps.branch-info.outputs.data).commit.sha }}")
          echo "COMMIT_HASH=$COMMIT_HASH" >> $GITHUB_ENV
          
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: refs/heads/${{ env.BRANCH_NAME }}
          #${{ env.COMMIT_HASH }}

      - name: Deploy to environment
        run: |
          echo "Deploying branch ${{ env.BRANCH_NAME }} to ${{ env.ENVIRONMENT_NAME }} environment..."



  

  
